name: CI (Quanta disabled)

on:
  push:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  pull_request:
    paths-ignore:
    - '.devcontainer/**'
    - '.gitpod.yml'
    - '.vscode/**'
  schedule:
    # Run against the last commit on the default branch on Friday at 8pm (UTC?)
    - cron: '0 20 * * 5'

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # https://github.com/marketplace/actions/skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    strategy:
      # Continue running other jobs in the matrix even if one fails.
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
          - 1.65.0  # MSRV
          - nightly # For checking minimum version dependencies.

    steps:
      - name: Checkout Moka
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Downgrade dependencies to minimal versions (Nightly only)
        if: ${{ matrix.rust == 'nightly' }}
        run: cargo update -Z minimal-versions

      - name: Pin some dependencies to specific versions (Nightly only)
        if: ${{ matrix.rust == 'nightly' }}
        run: ./.ci_extras/pin-crate-vers-nightly.sh

      - name: Pin some dependencies to specific versions (MSRV only)
        if: ${{ matrix.rust == '1.65.0' }}
        run: ./.ci_extras/pin-crate-vers-msrv.sh

      - name: Remove some examples (MSRV only)
        if: ${{ matrix.rust == '1.65.0' }}
        run: ./.ci_extras/remove-examples-msrv.sh

      - name: Run tests (debug, but no quanta feature)
        run: cargo test --no-default-features --features 'sync, atomic64'
        env:
          RUSTFLAGS: '--cfg rustver'

      - name: Run tests (release, but no quanta feature)
        run: cargo test --release --no-default-features --features 'sync, atomic64'
        env:
          RUSTFLAGS: '--cfg rustver'

      - name: Run tests (future feature, but no quanta and sync features)
        run: cargo test --no-default-features --features 'future, atomic64'

      - name: Run tests (future, sync and logging features, but no quanta feature)
        run: cargo test --no-default-features --features 'sync, future, atomic64, logging'

      - name: Run tests (sync feature, but no quanta feature, drop cache)
        run: cargo test --release --lib --no-default-features --features sync sync::cache::tests::ensure_gc_runs_when_dropping_cache -- --exact --ignored
