name: Kani CI

on:
  pull_request:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
      - CHANGELOG.md
      - README.md
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
      - CHANGELOG.md
      - README.md

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        # https://github.com/marketplace/actions/skip-duplicate-actions
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: 'same_content'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  run-kani:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Moka
        uses: actions/checkout@v4

      - name: Show CPU into
        run: |
          nproc
          lscpu
          free -m

      - name: Pin some dependencies to specific versions
        run: ./.ci_extras/pin-crate-vers-kani.sh

      - name: Show cargo tree
        run: cargo tree

      - name: Run Kani
        uses: model-checking/kani-github-action@v1.0
        with:
          args: --features 'sync, future'
