name: Kani CI

on:
  pull_request:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
      - CHANGELOG.md
      - README.md
  push:
    paths-ignore:
      - '.devcontainer/**'
      - '.gitpod.yml'
      - '.vscode/**'
      - CHANGELOG.md
      - README.md

jobs:
  run-kani:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Moka
        uses: actions/checkout@v3

      - name: Show CPU into
        run: |
          nproc
          lscpu
          free -m

      - name: Run Kani
        uses: model-checking/kani-github-action@v0.28
        with:
          args: --features 'sync, future'
